# Generated by Django 4.2 on 2026-01-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, help_text='Optional category, e.g. software, other', max_length=60),
        ),
    ]
