# Generated by Django 4.2 on 2026-01-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='period_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='details_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
