# Generated by Django 4.2 on 2026-01-16 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_degree_en_education_institution_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
