# Generated by Django 4.2 on 2026-01-16 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_skill_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('details', models.CharField(blank=True, max_length=300)),
                ('details_en', models.CharField(blank=True, max_length=300)),
                ('rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Software Skill',
                'verbose_name_plural': 'Software Skills',
            },
        ),
    ]
