# Generated by Django 4.2 on 2026-01-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_softwareskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='rating',
        ),
    ]
