# Generated by Django 4.2 on 2026-01-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_skill_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
