# Generated by Django 4.2 on 2026-01-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_personalinfo_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='details',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='details_en',
        ),
    ]
