# Generated by Django 4.2 on 2026-01-17 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_skill_details_remove_skill_details_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Preferred AI',
                'verbose_name_plural': 'Preferred AIs',
            },
        ),
    ]
